Add bookings
Peppilotta/java-shareit pull request #4
Opened 2023-05-29 19:50 UTC by Peppilotta

2023-05-30 17:15 UTC, kalitva requested changes

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +public class BookingDto implements Serializable {
А зачем реализовывать `Serializable`?

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +    private final InStorageUserService inStorageUserService;
Не очень зорошая идея - вайрить сервисы в мапперы. Лучше завайри сервисы в контроллере и там полуйчай и сетай объекты

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/dto/BookingMapper.java
> +        if (!Objects.equals(bookingDto.getStatus(), null)) {
Как насчет?
`if (bookingDto.getStatus() != null)) {`

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +//@RequiredArgsConstructor
Удали коммент

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/InStorageBookingService.java
> +public class InStorageBookingService implements BookingService {
Предлагаю удалить сервисы и репозитории, работающие с памятью

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/InStorageBookingService.java
> +        } else {
Нам точно нужен этот else?

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +}
Можно обойтись почти бех всех этих методов, фильтруя объекты используя спринговый `Specification`, попробуй

https://spring.io/blog/2011/04/26/advanced-spring-data-jpa-specifications-and-querydsl

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingSearchChoice.java
> +    static {
Давай как-нибудь обойдемся без статических блоков инициализации, это анти паттерн

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemDto deleteItem(@RequestHeader("X-Sharer-User-Id") long userId,
Давай вынесем `X-Sharer-User-Id` в константу

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> itemComments;
Предлагаю попробовать самостоятельно догадаться почему хранить `Comment` в хэшсете с такой реализацией как у тебя - плохая идея

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/InRepositoryItemService.java
> +    private final CommentMapper commentMapper;
Мы мапперы где будем вызывать? В сервисах или контроллерах? Либо все мапперы в сервисах, либо в контроллерах

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/InRepositoryItemService.java
> +                .filter(Objects::nonNull)
Разве из репозитория может вернуться null?

2023-05-30 17:15 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/InRepositoryItemService.java
> +        if (bookingRepository.existsByItemIdAndBookerIdAndStatusAndEndIsBefore
Давай инвертируем это условие

2023-05-30 17:15 UTC, kalitva commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:./db/shareit
по-моему что-то здесь не то, предыдущий вариант был правильный

2023-05-30 20:11 UTC, Peppilotta commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> itemComments;
не догадаюсь( почему?

2023-05-30 20:24 UTC, Peppilotta commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:./db/shareit
у меня вообще как-то криво всё собиралось. Но база действительно в памяти
и при предыдущем варианте вылетали предупреждения при компиляции
что делать?

2023-05-30 20:26 UTC, Peppilotta commented on src/main/java/ru/practicum/shareit/item/service/InRepositoryItemService.java
> +    private final CommentMapper commentMapper;
а в маппере репозиторий вызывать норм?
мне вообще автомаппер не очень понравился, больше сложностей чем упрощений

2023-05-31 17:51 UTC, Peppilotta commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +}
да, через Specification красивее, но нужно переписать всю логику
переписывать?

2023-06-01 20:39 UTC, kalitva approved these changes

2023-06-01 20:39 UTC, kalitva commented on pom.xml
> -												<minimum>0.9</minimum>
Покрытие тестами так-то нельзя выпиливать? Верни jacocо плагин

2023-06-01 20:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private static final String AUTHORIZATION_FOR_USER = "X-Sharer-User-Id";
`AUTHORIZATION_FOR_USER --> USER_ID_HEADER`

2023-06-01 20:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +            (@RequestParam(defaultValue = "ALL", required = false) String state,
Так скобочку не надо переносить

```java
public List<BookingDto> getItemsByStateAndOwner(
            @RequestParam(defaultValue = "ALL", required = false) String state,
```

2023-06-01 20:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +}
Не всю, только ту, которая касается запросов `/booking` и `/booking/owner`

2023-06-01 20:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    private Set<Comment> itemComments;
Тогда храни в списке

2023-06-01 20:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +public class UserDto implements Serializable {
А зачем `Serializable` не пойму? Мапструкт требует?

2023-06-01 20:39 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    @PostMapping("{itemId}/comment")
Спринг автоматически нормализует пути, но лучше лидирующий слэш не пропускать ` "/{itemId}/comment")` (проверь везде)

2023-06-01 20:39 UTC, kalitva commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:h2:mem:./db/shareit
Попробуй вернуть конфиг к исходному состоянию, вроде в этом задании его трогать и нет необходимости

2023-06-01 20:39 UTC, kalitva approved these changes

2023-06-01 20:41 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/InRepositoryItemService.java
> +    private final CommentMapper commentMapper;
Так делают, но на самом деле не очень, желательно обойтись без этого

2023-08-05 21:21 UTC, merged