Add item requests
Peppilotta/java-shareit pull request #5
Opened 2023-08-21 21:02 UTC by Peppilotta

2023-08-23 15:50 UTC, kalitva requested changes

2023-08-23 15:50 UTC, kalitva commented on pom.xml
> -                <groupId>org.jacoco</groupId>
Пожалуйста, верни плагин, он проверяет покрытие тестами

2023-08-23 15:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                              @RequestParam(defaultValue = "ALL", required = false) String state,
Наличие `defaultValue` автоматически выставляет `required = false`, можно не указывать

2023-08-23 15:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getBookingByState(userId, state, from, size);
1. Формируй здесь `Pageable` и его передавай в сервис
2. Не используй `Optional` как параметры методов

2023-08-23 15:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        checkFromAndSize(from, size);
Проверяй эти значения с помощью аннотаций `@Positive`, `@PositiveOrNull` прямо в парамтрах конструктора. Для этого надо над контроллером поставить спринговую `@Validated`

2023-08-23 15:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    EntityManager em;
Почему у нас в сервисе персистент-контекст? В сервисах нельзя, они для логики

2023-08-23 15:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/dto/RequestDto.java
> +    //implements Serializable
Удали коммент

2023-08-23 15:50 UTC, kalitva commented on src/main/java/ru/practicum/shareit/request/service/InRepositoryRequestService.java
> +    EntityManager em;
То же самое, удали, это грубая ошибка

2023-08-23 15:50 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    LocalDateTime dateTime = LocalDateTime.of(2023, 8, 12, 9, 0, 0, 0);
private

2023-08-23 15:50 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        ReflectionTestUtils.setField(bookingController, "bookingService", bookingService);
А `@MockBean` разве не инжектит сервис?

2023-08-23 15:50 UTC, kalitva commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +}
Еще желательно проверять вызовы сервисов с помощью `verify`, `verifyNoInteraction` и прочее
https://www.digitalocean.com/community/tutorials/mockito-verify

2023-08-28 18:32 UTC, Peppilotta commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +        return bookingService.getBookingByState(userId, state, from, size);
мне нужна помощь

не понимаю зачем. Нам ведь нужно вернуть в контроллер элементы, начиная с номера from до номера from + size а в Pageable from - номер страницы, а size  - размер страницы. Как это преобразовывать?

про Optional всё поняла. исправлю.

2023-08-29 19:23 UTC, Peppilotta commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +        ReflectionTestUtils.setField(bookingController, "bookingService", bookingService);
без этого не срабатывает

2023-09-02 18:00 UTC, kalitva approved these changes

2023-09-02 18:00 UTC, kalitva commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
>              "where b.item.owner.id = ?1 and b.status = ?2 " +
Используй имена вместо индексов, во всех запросах
`"where b.item.owner.id = :id and b.status = status "`

2023-09-02 18:00 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +    Page<Item> findByOwnerIdOrderById(long ownerId, Pageable pageable);
```java
    Page<Item> findByOwnerId(Long id, Pageable pageable);
```

Так не получится без запроса?

2023-09-02 18:00 UTC, kalitva commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +    List<Item> findAllByRequestIdOrderById(Long requestId);
`findAllByRequestIdOrderById --> findByRequestIdOrderById`

2023-09-02 18:00 UTC, kalitva commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +        return userService.getUserDto(id);
Нет необходимости добавлять `dto` в именах методов сервисов

2023-09-02 18:00 UTC, kalitva commented on src/main/resources/DataForTests.sql
> +INSERT INTO users
Скрипты для тестов клади в `src/test/resources`

2023-09-03 16:20 UTC, Peppilotta commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +        return userService.getUserDto(id);
а у меня их 2, и getUser, и getUserDto
оба нужны

2023-09-03 17:05 UTC, merged